/* This is a translation of ttttt.bf, generated by bftoc.py (by Paul Kaefer)
 * It was generated on Saturday, November 16, 2024 at 11:53AM
 */

#include <stdio.h>

void main(void)
{
    int size = 1000;
    int tape[size];
    int i = 0;

    /* Clearing the tape (array) */
    for (i=0; i<size; i++)
        tape[i] = 0;

    int ptr = 0;

    tape[ptr] += 14;
    while (tape[ptr] != 0)
    {
        ptr += 1;
        tape[ptr] += 3;
        ptr += 1;
        tape[ptr] += 3;
        ptr += 1;
        tape[ptr] += 3;
        ptr += 1;
        tape[ptr] += 6;
        ptr += 1;
        tape[ptr] += 3;
        ptr -= 5;
        tape[ptr] -= 1;
    }
    ptr += 2;
    tape[ptr] += 5;
    ptr += 1;
    tape[ptr] += 6;
    ptr += 1;
    tape[ptr] += 8;
    ptr += 2;
    tape[ptr] += 18;
    while (tape[ptr] != 0)
    {
        ptr += 1;
        tape[ptr] += 6;
        ptr += 1;
        tape[ptr] += 5;
        ptr += 1;
        tape[ptr] += 3;
        ptr += 1;
        tape[ptr] += 4;
        ptr += 1;
        tape[ptr] += 8;
        ptr += 1;
        tape[ptr] += 5;
        ptr += 1;
        tape[ptr] += 8;
        ptr += 1;
        tape[ptr] += 3;
        ptr += 1;
        tape[ptr] += 11;
        ptr += 1;
        tape[ptr] += 7;
        ptr += 1;
        tape[ptr] += 2;
        ptr += 1;
        tape[ptr] += 4;
        ptr += 1;
        tape[ptr] += 8;
        ptr += 1;
        tape[ptr] += 12;
        ptr += 1;
        tape[ptr] += 6;
        ptr += 1;
        tape[ptr] += 12;
        ptr += 1;
        tape[ptr] += 11;
        ptr -= 17;
        tape[ptr] -= 1;
    }
    ptr += 1;
    tape[ptr] += 12;
    ptr += 1;
    tape[ptr] += 10;
    ptr += 2;
    tape[ptr] += 3;
    ptr += 1;
    tape[ptr] += 4;
    ptr += 1;
    tape[ptr] += 12;
    ptr += 1;
    tape[ptr] += 1;
    ptr += 1;
    tape[ptr] += 15;
    ptr += 1;
    tape[ptr] += 1;
    ptr += 1;
    tape[ptr] += 10;
    ptr += 1;
    tape[ptr] += 9;
    ptr += 1;
    tape[ptr] += 3;
    ptr += 1;
    tape[ptr] += 4;
    ptr += 1;
    tape[ptr] += 16;
    ptr += 1;
    tape[ptr] += 6;
    ptr += 1;
    tape[ptr] += 1;
    ptr += 1;
    tape[ptr] += 16;

    for(int i = 0; i < 25;i++){
        printf("%c,", tape[i]);
    }



    while (tape[ptr] != 0)
    {
        ptr += 2;
        tape[ptr] = getchar();
        while (tape[ptr] != 0)
        {
            ptr -= 1;
            tape[ptr] += 3;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] += 1;
        while (tape[ptr] != 0)
        {
            ptr -= 1;
            tape[ptr] -= 1;
            ptr += 1;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        while (tape[ptr] != 0)
        {
        }
        ptr -= 1;
    }
    ptr -= 1;
    while (tape[ptr] != 0)
    {
        printf("%c",tape[ptr]);
        ptr -= 1;
    }

}

